### ISSUE TITLE
Cisco CSR 1000v messed-up interface names

### ISSUE THREAD

**Issue by ipspace** [hellt/vrnetlab#205] opened 2024-06-19 06:46 UTC
The Cisco CSR 1000v build process includes updating the QCOW VM image (good) which results in the management MAC address being stored "somewhere". The build process tries to cope with that, but it looks like the workaround no longer works with release 17.03.04a (that tells you how often people use it) -- once the container is started, the VM consistently boots with the first interface being GigabitEthernet2 (not GigabitEthernet1) and then everything goes down the drain.

The fix is simple: make the MAC address of the management interface constant (not random). It shouldn't matter as the management MAC address is not visible outside of the container.

I could submit the relevant (one-line) PR if you find the "let's fix the management MAC address" approach viable.

**Comment by hellt** [comment] 2024-06-19 06:49
I thought it is by design that GigEth2 is the first port =)
Yes, will gladly accept the fix

**Comment by ipspace** [comment] 2024-06-19 16:19
PR in #206

**Comment by hellt** [comment] 2024-06-20 07:35
thnx! merged.

**Closed by hellt** 2024-06-20 07:35 UTC
